services:
  - type: web
    name: Surveyapp
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: MONGO_DBNAME
        sync: false
      - key: MONGO_URI
        sync: false
