services:
  - type: web
    name: Surveyapp
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    runtime: python
    pythonVersion: 3.9
    disk:
      name: survey-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
